version: '3.0'

services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/posgresql/data
    ports:
      - 5432:5432
    volumes:
      - /var/lib/posgresql/data
    restart: always
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    environment:
      PORT: 3000
      POSTGRES_HOST: postgres
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.pnpm-store
    ports:
      - 3000:3000
      - 9229:9229
    command: pnpm preview
    depends_on:
      - postgres
    restart: always
volumes:
  pgdata:
